/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create a new organization with you as its owner, and log you in.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client */
        get: operations["get_client_clients__client_id__get"];
        put?: never;
        post?: never;
        /** Delete Client */
        delete: operations["delete_client_clients__client_id__delete"];
        options?: never;
        head?: never;
        /** Update Client */
        patch: operations["update_client_clients__client_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Newest first. Filter by `status` (e.g. for the job board) or `client_id`.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Job */
        patch: operations["update_job_jobs__job_id__patch"];
        trace?: never;
    };
    "/jobs/{job_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Payments
         * @description The job's payments (voided ones included, for the audit trail) and balance.
         */
        get: operations["list_payments_jobs__job_id__payments_get"];
        put?: never;
        /** Record Payment */
        post: operations["record_payment_jobs__job_id__payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/payments/{payment_id}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Void Payment
         * @description Stop a mistaken payment from counting. It stays in the history.
         */
        post: operations["void_payment_jobs__job_id__payments__payment_id__void_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Job Quotes
         * @description All versions of a job's quote, oldest first.
         */
        get: operations["list_job_quotes_jobs__job_id__quotes_get"];
        put?: never;
        /**
         * Create Quote
         * @description Create version 1 for a job. Later versions come from revisions.
         */
        post: operations["create_quote_jobs__job_id__quotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Organization
         * @description Owner only. New quotes copy these rates; existing quotes keep theirs.
         */
        patch: operations["update_organization_organization_patch"];
        trace?: never;
    };
    "/public/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View Quote */
        get: operations["view_quote_public_quote_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/quote/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_public_quote_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/quote/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline */
        post: operations["decline_public_quote_decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/quote/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote Pdf */
        get: operations["quote_pdf_public_quote_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quote_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quote */
        get: operations["get_quote_quotes__quote_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Quote */
        patch: operations["update_quote_quotes__quote_id__patch"];
        trace?: never;
    };
    "/quotes/{quote_id}/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Area */
        post: operations["add_area_quotes__quote_id__areas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quote_id}/areas/{area_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Area */
        delete: operations["delete_area_quotes__quote_id__areas__area_id__delete"];
        options?: never;
        head?: never;
        /** Update Area */
        patch: operations["update_area_quotes__quote_id__areas__area_id__patch"];
        trace?: never;
    };
    "/quotes/{quote_id}/line-items/{line_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Override */
        put: operations["set_override_quotes__quote_id__line_items__line_id__override_put"];
        post?: never;
        /** Clear Override */
        delete: operations["clear_override_quotes__quote_id__line_items__line_id__override_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quote_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote Pdf */
        get: operations["quote_pdf_quotes__quote_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quote_id}/refresh-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Rates
         * @description Pull current organization and template rates into this draft.
         */
        post: operations["refresh_rates_quotes__quote_id__refresh_rates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quote_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Revision
         * @description New draft version copying this (latest, non-draft) version.
         */
        post: operations["create_revision_quotes__quote_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quote_id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Quote
         * @description Freeze the draft and create the client's link (shown this once).
         */
        post: operations["send_quote_quotes__quote_id__send_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/{quote_id}/share-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Link
         * @description A new client link for a sent quote. The previous link stops working.
         */
        post: operations["regenerate_link_quotes__quote_id__share_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description System templates plus your organization's own, with their items.
         */
        get: operations["list_templates_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApproveRequest */
        ApproveRequest: {
            /**
             * Accept Terms
             * @description The client ticked 'I agree'
             * @constant
             */
            accept_terms: true;
            /** Name */
            name: string;
        };
        /** AreaCreate */
        AreaCreate: {
            /** Coats */
            coats?: number | null;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | string;
            /**
             * Template Item Id
             * Format: uuid
             */
            template_item_id: string;
        };
        /** AreaOut */
        AreaOut: {
            /** Coats */
            coats: number;
            /** Coverage Per Material Unit */
            coverage_per_material_unit: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Labor Hours Per Unit */
            labor_hours_per_unit: string;
            /** Material Name */
            material_name: string;
            /** Material Unit */
            material_unit: string;
            /** Material Unit Cost Cents */
            material_unit_cost_cents: number;
            measure_type: components["schemas"]["MeasureType"];
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Quantity */
            quantity: string;
            /** Template Item Id */
            template_item_id: string | null;
            /** Waste Factor */
            waste_factor: string;
        };
        /** AreaUpdate */
        AreaUpdate: {
            /** Coats */
            coats?: number | null;
            /** Name */
            name?: string | null;
            /** Quantity */
            quantity?: number | string | null;
        };
        /** ClientCreate */
        ClientCreate: {
            /** Address */
            address?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
        };
        /** ClientOut */
        ClientOut: {
            /** Address */
            address: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
        };
        /**
         * ClientUpdate
         * @description PATCH: every field optional; send null to clear an optional field.
         */
        ClientUpdate: {
            /** Address */
            address?: string | null;
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** CurrentUserOut */
        CurrentUserOut: {
            /** Email */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["UserRole"];
        };
        /** DeclineRequest */
        DeclineRequest: {
            /** Name */
            name: string;
            /** Reason */
            reason?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreate */
        JobCreate: {
            /** Address */
            address?: string | null;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Title */
            title: string;
        };
        /** JobOut */
        JobOut: {
            /** Address */
            address: string | null;
            /**
             * Allowed Transitions
             * @default []
             */
            allowed_transitions: components["schemas"]["JobStatus"][];
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Client Name */
            client_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["JobStatus"];
            /** Title */
            title: string;
        };
        /** JobPaymentsOut */
        JobPaymentsOut: {
            job_status: components["schemas"]["JobStatus"];
            /** Payments */
            payments: components["schemas"]["PaymentOut"][];
            summary: components["schemas"]["PaymentSummaryOut"];
            /**
             * Today
             * Format: date
             */
            today: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "quoted" | "approved" | "scheduled" | "in_progress" | "completed" | "paid";
        /** JobUpdate */
        JobUpdate: {
            /** Address */
            address?: string | null;
            status?: components["schemas"]["JobStatus"] | null;
            /** Title */
            title?: string | null;
        };
        /**
         * LineItemKind
         * @description Which calculated line a quote line item is. Mirrors the estimating
         *     engine's LineKind; the engine keeps its own copy so it never imports
         *     from the database layer.
         * @enum {string}
         */
        LineItemKind: "material" | "labor";
        /** LineItemOut */
        LineItemOut: {
            /** Area Id */
            area_id: string | null;
            /** Description */
            description: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Override */
            is_override: boolean;
            kind: components["schemas"]["LineItemKind"];
            /** Override Quantity */
            override_quantity: string | null;
            /** Override Unit Price Cents */
            override_unit_price_cents: number | null;
            /** Quantity */
            quantity: string;
            /** Total Cents */
            total_cents: number;
            /** Unit */
            unit: string;
            /** Unit Price Cents */
            unit_price_cents: number;
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            organization: components["schemas"]["OrganizationOut"];
            user: components["schemas"]["CurrentUserOut"];
        };
        /**
         * MeasureType
         * @description How an area/template item is measured. Trade-agnostic on purpose.
         * @enum {string}
         */
        MeasureType: "area" | "linear" | "count";
        /** OrganizationOut */
        OrganizationOut: {
            /** Default Labor Rate Cents */
            default_labor_rate_cents: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Logo Url */
            logo_url: string | null;
            /** Name */
            name: string;
            /** Tax Rate */
            tax_rate: string;
        };
        /** OrganizationUpdate */
        OrganizationUpdate: {
            /** Default Labor Rate Cents */
            default_labor_rate_cents?: number | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Name */
            name?: string | null;
            /** Tax Rate */
            tax_rate?: number | string | null;
        };
        /**
         * OverrideRequest
         * @description Replace a line's quantity and/or unit price. The total is derived.
         */
        OverrideRequest: {
            /** Quantity */
            quantity?: number | string | null;
            /** Unit Price Cents */
            unit_price_cents?: number | null;
        };
        /** Page[ClientOut] */
        Page_ClientOut_: {
            /** Items */
            items: components["schemas"]["ClientOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[JobOut] */
        Page_JobOut_: {
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PaymentCreate */
        PaymentCreate: {
            /** Amount Cents */
            amount_cents: number;
            kind: components["schemas"]["PaymentKind"];
            /** Method */
            method?: string | null;
            /**
             * Received On
             * Format: date
             */
            received_on: string;
        };
        /**
         * PaymentKind
         * @enum {string}
         */
        PaymentKind: "deposit" | "final";
        /** PaymentOut */
        PaymentOut: {
            /** Amount Cents */
            amount_cents: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["PaymentKind"];
            /** Method */
            method: string | null;
            /**
             * Received On
             * Format: date
             */
            received_on: string;
            /** Void Reason */
            void_reason: string | null;
            /** Voided At */
            voided_at: string | null;
        };
        /** PaymentSummaryOut */
        PaymentSummaryOut: {
            /** Amount Due Cents */
            amount_due_cents: number | null;
            /** Balance Cents */
            balance_cents: number | null;
            /** Deposit Outstanding Cents */
            deposit_outstanding_cents: number | null;
            /** Deposit Required Cents */
            deposit_required_cents: number | null;
            /** Paid Cents */
            paid_cents: number;
        };
        /** PublicLineOut */
        PublicLineOut: {
            /** Description */
            description: string;
            /** Quantity */
            quantity: string;
            /** Total Cents */
            total_cents: number;
            /** Unit */
            unit: string;
            /** Unit Price Cents */
            unit_price_cents: number;
        };
        /** PublicQuoteOut */
        PublicQuoteOut: {
            /** Approved At */
            approved_at: string | null;
            /** Approved By Name */
            approved_by_name: string | null;
            /** Can Decide */
            can_decide: boolean;
            /** Client Name */
            client_name: string;
            /** Declined At */
            declined_at: string | null;
            /** Declined By Name */
            declined_by_name: string | null;
            /** Deposit Required Cents */
            deposit_required_cents: number;
            /** Is Latest Version */
            is_latest_version: boolean;
            /** Job Address */
            job_address: string | null;
            /** Job Title */
            job_title: string;
            /** Lines */
            lines: components["schemas"]["PublicLineOut"][];
            /**
             * Link Expires At
             * Format: date-time
             */
            link_expires_at: string;
            /** Organization Name */
            organization_name: string;
            /** Sent At */
            sent_at: string | null;
            status: components["schemas"]["QuoteStatus"];
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Tax Cents */
            tax_cents: number;
            /** Tax Rate */
            tax_rate: string;
            /** Total Cents */
            total_cents: number;
            /** Version */
            version: number;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Approved At */
            approved_at: string | null;
            /** Approved By Name */
            approved_by_name: string | null;
            /** Areas */
            areas: components["schemas"]["AreaOut"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Decline Reason */
            decline_reason: string | null;
            /** Declined At */
            declined_at: string | null;
            /** Declined By Name */
            declined_by_name: string | null;
            /** Deposit Required Cents */
            deposit_required_cents: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Labor Rate Cents */
            labor_rate_cents: number;
            /** Line Items */
            line_items: components["schemas"]["LineItemOut"][];
            /** Sent At */
            sent_at: string | null;
            status: components["schemas"]["QuoteStatus"];
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Tax Cents */
            tax_cents: number;
            /** Tax Rate */
            tax_rate: string;
            /** Token Expires At */
            token_expires_at: string | null;
            /** Total Cents */
            total_cents: number;
            /** Version */
            version: number;
        };
        /**
         * QuoteStatus
         * @enum {string}
         */
        QuoteStatus: "draft" | "sent" | "approved" | "declined";
        /** QuoteSummaryOut */
        QuoteSummaryOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deposit Required Cents */
            deposit_required_cents: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["QuoteStatus"];
            /** Subtotal Cents */
            subtotal_cents: number;
            /** Tax Cents */
            tax_cents: number;
            /** Total Cents */
            total_cents: number;
            /** Version */
            version: number;
        };
        /** QuoteUpdate */
        QuoteUpdate: {
            /** Deposit Required Cents */
            deposit_required_cents: number;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unreachable";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unavailable";
        };
        /** SendQuoteResponse */
        SendQuoteResponse: {
            link: components["schemas"]["ShareLinkOut"];
            quote: components["schemas"]["QuoteOut"];
        };
        /**
         * ShareLinkOut
         * @description The raw link token. Returned only at creation: the server keeps just
         *     its hash, so it can't be shown again (make a new link instead).
         */
        ShareLinkOut: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Token */
            token: string;
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Organization Name */
            organization_name: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** TemplateItemOut */
        TemplateItemOut: {
            /** Coverage Per Material Unit */
            coverage_per_material_unit: string;
            /** Default Coats */
            default_coats: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Labor Hours Per Unit */
            labor_hours_per_unit: string;
            /** Material Name */
            material_name: string;
            /** Material Unit */
            material_unit: string;
            /** Material Unit Cost Cents */
            material_unit_cost_cents: number;
            measure_type: components["schemas"]["MeasureType"];
            /** Name */
            name: string;
            /** Waste Factor */
            waste_factor: string;
        };
        /** TemplateOut */
        TemplateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Items */
            items: components["schemas"]["TemplateItemOut"][];
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: string | null;
            /** Trade */
            trade: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "owner" | "staff";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoidRequest */
        VoidRequest: {
            /** Reason */
            reason: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_clients_get: {
        parameters: {
            query?: {
                /** @description Max items to return */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ClientOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_clients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_client_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                client_id?: string | null;
                /** @description Max items to return */
                limit?: number;
                /** @description Items to skip */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payments_jobs__job_id__payments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPaymentsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_payment_jobs__job_id__payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPaymentsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    void_payment_jobs__job_id__payments__payment_id__void_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                payment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoidRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPaymentsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_quotes_jobs__job_id__quotes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteSummaryOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_quote_jobs__job_id__quotes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    update_organization_organization_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    view_quote_public_quote_get: {
        parameters: {
            query?: never;
            header: {
                "X-Quote-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicQuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_public_quote_approve_post: {
        parameters: {
            query?: never;
            header: {
                "X-Quote-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicQuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_public_quote_decline_post: {
        parameters: {
            query?: never;
            header: {
                "X-Quote-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicQuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_pdf_public_quote_pdf_get: {
        parameters: {
            query?: never;
            header: {
                "X-Quote-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The quote as a PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quote_quotes__quote_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_quote_quotes__quote_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_area_quotes__quote_id__areas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_area_quotes__quote_id__areas__area_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
                area_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_area_quotes__quote_id__areas__area_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
                area_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_override_quotes__quote_id__line_items__line_id__override_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
                line_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_override_quotes__quote_id__line_items__line_id__override_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
                line_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_pdf_quotes__quote_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The quote as a PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_rates_quotes__quote_id__refresh_rates_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_revision_quotes__quote_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_quote_quotes__quote_id__send_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendQuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_link_quotes__quote_id__share_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quote_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareLinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
        };
    };
}
