"""payments: received_on date and voiding

- received_at (timestamp) becomes received_on (DATE): a payment date is a
  calendar date, and a timestamp could shift it across midnight in UTC.
- voided_at + void_reason: payments are voided, never deleted.

Hand-written, not autogenerated: autogenerate would express the rename as
"drop received_at, add received_on", which would DESTROY existing data. A
real rename with an explicit USING conversion keeps every row.

Revision ID: 778772a6bfd2
Revises: 44fb1b56a2e4
Create Date: 2026-09-25 19:10:40.396437

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic to order migrations.
revision: str = "778772a6bfd2"
down_revision: str | Sequence[str] | None = "44fb1b56a2e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.alter_column(
        "payments",
        "received_at",
        new_column_name="received_on",
        type_=sa.Date(),
        # Timestamps are converted to dates in UTC. (The table is empty today,
        # but a migration should be correct for data too.)
        postgresql_using="(received_at AT TIME ZONE 'UTC')::date",
    )
    op.add_column("payments", sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("payments", sa.Column("void_reason", sa.Text(), nullable=True))
    op.create_check_constraint(
        op.f("ck_payments_void_recorded"), "payments", "(voided_at IS NULL) = (void_reason IS NULL)"
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_payments_void_recorded"), "payments", type_="check")
    op.drop_column("payments", "void_reason")
    op.drop_column("payments", "voided_at")
    op.alter_column(
        "payments",
        "received_on",
        new_column_name="received_at",
        type_=sa.DateTime(timezone=True),
        postgresql_using="received_on::timestamp AT TIME ZONE 'UTC'",
    )
