"""snapshot rates and store line overrides

Rule 6 (price snapshots): quotes now carry copies of every rate they use, so
recalculation never reads templates or organization settings.
- quotes: labor_rate_cents, tax_rate (copied from the organization)
- quote_areas: the template item's material/coverage/waste/labor rates, plus a
  position (display order; created_at ties within one transaction)
- quote_line_items: kind (material|labor) + separately stored override values

Autogenerated, then hand-edited:
- Autogenerate can't detect CHECK constraints added to existing tables, so
  every CHECK below was written by hand (names follow the naming convention,
  matching what the models declare).
- The kind enum uses create_constraint=False plus one explicit CHECK, as in
  the initial migration.
- NOT NULL columns without defaults are safe only because no quotes exist
  yet; on tables with data this needs nullable -> backfill -> NOT NULL.

Revision ID: ce5af0442de7
Revises: 65913c83900a
Create Date: 2026-09-25 16:21:55.505506

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic to order migrations.
revision: str = "ce5af0442de7"
down_revision: str | Sequence[str] | None = "65913c83900a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (table, constraint name without the ck_<table>_ prefix, SQL condition)
CHECKS = [
    ("quotes", "labor_rate_non_negative", "labor_rate_cents >= 0"),
    ("quotes", "tax_rate_range", "tax_rate >= 0 AND tax_rate <= 1"),
    ("quote_areas", "material_cost_non_negative", "material_unit_cost_cents >= 0"),
    ("quote_areas", "coverage_positive", "coverage_per_material_unit > 0"),
    ("quote_areas", "waste_non_negative", "waste_factor >= 0"),
    ("quote_areas", "labor_non_negative", "labor_hours_per_unit >= 0"),
    ("quote_areas", "position_non_negative", "position >= 0"),
    ("quote_line_items", "line_item_kind", "kind IN ('material', 'labor')"),
    (
        "quote_line_items",
        "override_values_non_negative",
        "(override_quantity IS NULL OR override_quantity >= 0)"
        " AND (override_unit_price_cents IS NULL OR override_unit_price_cents >= 0)",
    ),
    (
        "quote_line_items",
        "override_flag_consistent",
        "is_override = (override_quantity IS NOT NULL OR override_unit_price_cents IS NOT NULL)",
    ),
]


def upgrade() -> None:
    op.add_column("quotes", sa.Column("labor_rate_cents", sa.BigInteger(), nullable=False))
    op.add_column("quotes", sa.Column("tax_rate", sa.Numeric(precision=6, scale=5), nullable=False))

    op.add_column("quote_areas", sa.Column("position", sa.Integer(), nullable=False))
    op.add_column("quote_areas", sa.Column("material_name", sa.String(length=200), nullable=False))
    op.add_column("quote_areas", sa.Column("material_unit", sa.String(length=50), nullable=False))
    op.add_column(
        "quote_areas", sa.Column("material_unit_cost_cents", sa.BigInteger(), nullable=False)
    )
    op.add_column(
        "quote_areas",
        sa.Column("coverage_per_material_unit", sa.Numeric(precision=10, scale=3), nullable=False),
    )
    op.add_column(
        "quote_areas", sa.Column("waste_factor", sa.Numeric(precision=5, scale=4), nullable=False)
    )
    op.add_column(
        "quote_areas",
        sa.Column("labor_hours_per_unit", sa.Numeric(precision=10, scale=5), nullable=False),
    )

    op.add_column(
        "quote_line_items",
        sa.Column(
            "kind",
            sa.Enum(
                "material",
                "labor",
                name="line_item_kind",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "quote_line_items",
        sa.Column("override_quantity", sa.Numeric(precision=12, scale=3), nullable=True),
    )
    op.add_column(
        "quote_line_items", sa.Column("override_unit_price_cents", sa.BigInteger(), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_quote_line_items_area_id_kind"), "quote_line_items", ["area_id", "kind"]
    )

    for table, name, condition in CHECKS:
        op.create_check_constraint(op.f(f"ck_{table}_{name}"), table, condition)


def downgrade() -> None:
    for table, name, _ in reversed(CHECKS):
        op.drop_constraint(op.f(f"ck_{table}_{name}"), table, type_="check")

    op.drop_constraint(op.f("uq_quote_line_items_area_id_kind"), "quote_line_items", type_="unique")
    op.drop_column("quote_line_items", "override_unit_price_cents")
    op.drop_column("quote_line_items", "override_quantity")
    op.drop_column("quote_line_items", "kind")
    op.drop_column("quote_areas", "labor_hours_per_unit")
    op.drop_column("quote_areas", "waste_factor")
    op.drop_column("quote_areas", "coverage_per_material_unit")
    op.drop_column("quote_areas", "material_unit_cost_cents")
    op.drop_column("quote_areas", "material_unit")
    op.drop_column("quote_areas", "material_name")
    op.drop_column("quote_areas", "position")
    op.drop_column("quotes", "tax_rate")
    op.drop_column("quotes", "labor_rate_cents")
