"""quote sending and decline details; rate limit counters

- quotes: sent_at, declined_at, declined_by_name, decline_reason
- rate_limit_counters: per-key, per-window request counts for public endpoints

Autogenerated, then hand-edited: autogenerate can't see CHECK constraints
added to an existing table, so the two quotes CHECKs are added by hand.

Revision ID: 44fb1b56a2e4
Revises: ce5af0442de7
Create Date: 2026-09-25 18:24:33.178474

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic to order migrations.
revision: str = "44fb1b56a2e4"
down_revision: str | Sequence[str] | None = "ce5af0442de7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "rate_limit_counters",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("count >= 1", name=op.f("ck_rate_limit_counters_count_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_limit_counters")),
        sa.UniqueConstraint(
            "key", "window_start", name=op.f("uq_rate_limit_counters_key_window_start")
        ),
    )
    op.create_index(
        op.f("ix_rate_limit_counters_window_start"),
        "rate_limit_counters",
        ["window_start"],
        unique=False,
    )
    op.add_column("quotes", sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("quotes", sa.Column("declined_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("quotes", sa.Column("declined_by_name", sa.String(length=200), nullable=True))
    op.add_column("quotes", sa.Column("decline_reason", sa.Text(), nullable=True))
    op.create_check_constraint(
        op.f("ck_quotes_decline_recorded"),
        "quotes",
        "status <> 'declined' OR (declined_at IS NOT NULL AND declined_by_name IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_quotes_sent_recorded"), "quotes", "status = 'draft' OR sent_at IS NOT NULL"
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_quotes_sent_recorded"), "quotes", type_="check")
    op.drop_constraint(op.f("ck_quotes_decline_recorded"), "quotes", type_="check")
    op.drop_column("quotes", "decline_reason")
    op.drop_column("quotes", "declined_by_name")
    op.drop_column("quotes", "declined_at")
    op.drop_column("quotes", "sent_at")
    op.drop_index(op.f("ix_rate_limit_counters_window_start"), table_name="rate_limit_counters")
    op.drop_table("rate_limit_counters")
