"""initial schema

Creates all MVP tables. Autogenerated, then hand-edited:
- Enum columns use create_constraint=False, and each enum's allowed values are
  enforced by exactly one explicit CHECK named ck_<table>_<enum_name>.
  Autogenerate emitted the same CHECK up to three times (once from the Enum
  type itself), which collided under our naming convention and failed.

Revision ID: a6e03b9abfbd
Revises:
Create Date: 2026-09-25 15:01:13.486757

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic to order migrations.
revision: str = "a6e03b9abfbd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("default_labor_rate_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=6, scale=5), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_labor_rate_cents >= 0", name=op.f("ck_organizations_labor_rate_non_negative")
        ),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 1", name=op.f("ck_organizations_tax_rate_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "clients",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_clients_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_clients_organization_id_id")),
    )
    op.create_index(
        op.f("ix_clients_organization_id"), "clients", ["organization_id"], unique=False
    )
    op.create_table(
        "trade_templates",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("trade", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_trade_templates_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_templates")),
        sa.UniqueConstraint(
            "organization_id",
            "trade",
            "name",
            name=op.f("uq_trade_templates_organization_id_trade_name"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "role",
            sa.Enum("owner", "staff", name="user_role", native_enum=False, create_constraint=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("role IN ('owner', 'staff')", name=op.f("ck_users_user_role")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "quoted",
                "approved",
                "scheduled",
                "in_progress",
                "completed",
                "paid",
                name="job_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="quoted",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('quoted', 'approved', 'scheduled', 'in_progress', 'completed', 'paid')",
            name=op.f("ck_jobs_job_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "client_id"],
            ["clients.organization_id", "clients.id"],
            name=op.f("fk_jobs_organization_id_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("organization_id", "id", name=op.f("uq_jobs_organization_id_id")),
    )
    op.create_index(op.f("ix_jobs_client_id"), "jobs", ["client_id"], unique=False)
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_table(
        "template_items",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "measure_type",
            sa.Enum(
                "area",
                "linear",
                "count",
                name="measure_type",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column("material_name", sa.String(length=200), nullable=False),
        sa.Column("material_unit", sa.String(length=50), nullable=False),
        sa.Column("material_unit_cost_cents", sa.BigInteger(), nullable=False),
        sa.Column("coverage_per_material_unit", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("waste_factor", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("labor_hours_per_unit", sa.Numeric(precision=10, scale=5), nullable=False),
        sa.Column("default_coats", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "measure_type IN ('area', 'linear', 'count')",
            name=op.f("ck_template_items_measure_type"),
        ),
        sa.CheckConstraint(
            "coverage_per_material_unit > 0", name=op.f("ck_template_items_coverage_positive")
        ),
        sa.CheckConstraint(
            "default_coats >= 1", name=op.f("ck_template_items_default_coats_positive")
        ),
        sa.CheckConstraint(
            "labor_hours_per_unit >= 0", name=op.f("ck_template_items_labor_non_negative")
        ),
        sa.CheckConstraint(
            "material_unit_cost_cents >= 0",
            name=op.f("ck_template_items_material_cost_non_negative"),
        ),
        sa.CheckConstraint("waste_factor >= 0", name=op.f("ck_template_items_waste_non_negative")),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["trade_templates.id"],
            name=op.f("fk_template_items_template_id_trade_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_items")),
        sa.UniqueConstraint("template_id", "name", name=op.f("uq_template_items_template_id_name")),
    )
    op.create_table(
        "payments",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("amount_cents", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "deposit", "final", name="payment_kind", native_enum=False, create_constraint=False
            ),
            nullable=False,
        ),
        sa.Column("method", sa.String(length=50), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("kind IN ('deposit', 'final')", name=op.f("ck_payments_payment_kind")),
        sa.CheckConstraint("amount_cents > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["jobs.organization_id", "jobs.id"],
            name=op.f("fk_payments_organization_id_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_payments_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_job_id"), "payments", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_payments_organization_id"), "payments", ["organization_id"], unique=False
    )
    op.create_table(
        "quotes",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "sent",
                "approved",
                "declined",
                name="quote_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("public_token_hash", sa.String(length=64), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subtotal_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tax_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("total_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("deposit_required_cents", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_name", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status <> 'approved' OR (approved_at IS NOT NULL AND approved_by_name IS NOT NULL)",
            name=op.f("ck_quotes_approval_recorded"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'sent', 'approved', 'declined')",
            name=op.f("ck_quotes_quote_status"),
        ),
        sa.CheckConstraint(
            "(public_token_hash IS NULL) = (token_expires_at IS NULL)",
            name=op.f("ck_quotes_token_hash_and_expiry_together"),
        ),
        sa.CheckConstraint(
            "deposit_required_cents <= total_cents", name=op.f("ck_quotes_deposit_within_total")
        ),
        sa.CheckConstraint(
            "subtotal_cents >= 0 AND tax_cents >= 0 AND deposit_required_cents >= 0",
            name=op.f("ck_quotes_amounts_non_negative"),
        ),
        sa.CheckConstraint(
            "total_cents = subtotal_cents + tax_cents", name=op.f("ck_quotes_total_is_sum")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_quotes_version_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id", "job_id"],
            ["jobs.organization_id", "jobs.id"],
            name=op.f("fk_quotes_organization_id_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_quotes_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotes")),
        sa.UniqueConstraint("job_id", "version", name=op.f("uq_quotes_job_id_version")),
        sa.UniqueConstraint("public_token_hash", name=op.f("uq_quotes_public_token_hash")),
    )
    op.create_index(op.f("ix_quotes_organization_id"), "quotes", ["organization_id"], unique=False)
    op.create_table(
        "quote_areas",
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "measure_type",
            sa.Enum(
                "area",
                "linear",
                "count",
                name="measure_type",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("template_item_id", sa.Uuid(), nullable=True),
        sa.Column("coats", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "measure_type IN ('area', 'linear', 'count')", name=op.f("ck_quote_areas_measure_type")
        ),
        sa.CheckConstraint("coats >= 1", name=op.f("ck_quote_areas_coats_positive")),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_quote_areas_quantity_non_negative")),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
            name=op.f("fk_quote_areas_quote_id_quotes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["template_item_id"],
            ["template_items.id"],
            name=op.f("fk_quote_areas_template_item_id_template_items"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_areas")),
        sa.UniqueConstraint("quote_id", "id", name=op.f("uq_quote_areas_quote_id_id")),
    )
    op.create_index(
        op.f("ix_quote_areas_template_item_id"), "quote_areas", ["template_item_id"], unique=False
    )
    op.create_table(
        "quote_line_items",
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("area_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("unit_price_cents", sa.BigInteger(), nullable=False),
        sa.Column("total_cents", sa.BigInteger(), nullable=False),
        sa.Column("is_override", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name=op.f("ck_quote_line_items_quantity_non_negative")),
        sa.CheckConstraint(
            "unit_price_cents >= 0 AND total_cents >= 0",
            name=op.f("ck_quote_line_items_amounts_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["quote_id", "area_id"],
            ["quote_areas.quote_id", "quote_areas.id"],
            name=op.f("fk_quote_line_items_quote_id_area_id_quote_areas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
            name=op.f("fk_quote_line_items_quote_id_quotes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quote_line_items")),
    )
    op.create_index(
        op.f("ix_quote_line_items_area_id"), "quote_line_items", ["area_id"], unique=False
    )
    op.create_index(
        op.f("ix_quote_line_items_quote_id"), "quote_line_items", ["quote_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quote_line_items_quote_id"), table_name="quote_line_items")
    op.drop_index(op.f("ix_quote_line_items_area_id"), table_name="quote_line_items")
    op.drop_table("quote_line_items")
    op.drop_index(op.f("ix_quote_areas_template_item_id"), table_name="quote_areas")
    op.drop_table("quote_areas")
    op.drop_index(op.f("ix_quotes_organization_id"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_payments_organization_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_job_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_table("template_items")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_client_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("trade_templates")
    op.drop_index(op.f("ix_clients_organization_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_table("organizations")
    # ### end Alembic commands ###
